Update classes-wind-degrees.scss
 ERROR  Failed to compile with 1 errors                                                                                            10:22:55

 error  in ./node_modules/weathericons/sass/weather-icons-wind.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: compound selectors may no longer be extended.
Consider `@extend .wi-wind, .towards-0-deg` instead.
See http://bit.ly/ExtendCompound for details.

    ╷
727 │   @extend .wi-wind.towards-0-deg;
    │           ^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/weathericons/sass/icon-classes/classes-wind-degrees.scss 727:11  root stylesheet